print(f'*** Recetas de Cocina***')
nombre_receta = input('Ingresa el nombre: ')
ingredientes = input('Ingresa los ingredientes: ')
tiempo_preparacion = int(input('Ingresa el tiempo de preparacion (min)'))
dificultada_preparacion = input('Ingresa la dificultad: ')
print('------------------------')
print(f'Nombre receta: {nombre_receta}')
print(f'Ingredientes: {ingredientes}')
print(f'Timepo de preparacion: {tiempo_preparacion}')
print(f'Dificultad: {dificultad_preparacion}')